services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "6543:5432"

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://workplace:password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      MM_SERVICESETTINGS_SITEURL: http://127.0.0.1:8065
      MM_CONFIG: /mattermost/config/config.json
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_config:/mattermost/config
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client_plugins:/mattermost/client/plugins
      - mattermost_bleve:/mattermost/bleve-indexes

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://workplace:password@postgres:5432/workplace
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  ui:
    build: ./ui
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - mattermost
      - ui
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  pg_data:



  mattermost_data:
  mattermost_config:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client_plugins:
  mattermost_bleve:
